name: pokedex_pro
description: PokÃ©Dex Pro - Flutter Clean Architecture Lab
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  fl_chart: ^0.65.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
